name: CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-prod-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-prod-

      # Composer Install
      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-progress --ignore-platform-reqs

      # Node Install
      - name: Node install Dependencies
        run: npm install

      # Build Assets
      - name: Build assets
        run: |
          npm run production
          rm -rf node_modules && npm install --production

      # Update Version
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Update Version in WordPress files
        run: |
          sed -i -E 's/([[:blank:]]*\*[[:blank:]]*Version:[[:blank:]]*).*/\1${{ env.RELEASE_VERSION }}/' ${{ github.event.repository.name }}.php
          sed -i -E 's/([[:blank:]]*\$version[[:blank:]]*=[[:blank:]]*")(.*)(".*)/\1${{ env.RELEASE_VERSION }}\3/' ${{ github.event.repository.name }}.php

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            ${{ github.event.repository.name }}.php
          commit-msg: Update Version in WordPress specific files
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Delete Development Files
      - shell: bash
        run: |
          find . -name "composer.json" -type f -delete && find . -name "composer.lock" -type f -delete
          find . -name "package.json" -type f -delete && find . -name "package-lock.json" -type f -delete
          rm -rf .git && find . -name ".gitignore" -type f -delete
          rm -rf .github

      # Zip everything
      - shell: bash
        run: |
          cd ..
          sudo apt-get install zip
          zip -r ${{ github.event.repository.name }}.zip ./*
          mkdir ${{ github.workspace }}/dist
          mv ${{ github.event.repository.name }}.zip ${{ github.workspace }}/dist

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          path: |
            ${{ github.workspace }}/dist/${{ github.event.repository.name }}.zip
          name: build
          retention-days: 5

  deploy:
    # Wait for buld job to finish
    needs: build

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Upload new Version
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PEM }}
          source: ${{ github.event.repository.name }}.zip
          target: ${{ secrets.PATH }}

      - name: Update Version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PEM }}
          port: 22
          script: |
            sed -i 's/"version":[^,]*/"version": "${{ env.RELEASE_VERSION }}"/g' ${{ secrets.PATH }}/details.json
