name: PHP Test/Analyse

on: [push, pull_request]

jobs:
  phpstan:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-dev-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-dev-
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: PHPSTAN
        run: composer run static-analyse
